import { Country } from './country.type';

export const defaultCountries: Country[] = [
  { name: 'Grenada', flag: '🇬🇩' },
  { name: 'Switzerland', flag: '🇨🇭' },
  { name: 'Sierra Leone', flag: '🇸🇱' },
  { name: 'Hungary', flag: '🇭🇺' },
  { name: 'Barbados', flag: '🇧🇧' },
  { name: 'Ivory Coast', flag: '🇨🇮' },
  { name: 'Tunisia', flag: '🇹🇳' },
  { name: 'Italy', flag: '🇮🇹' },
  { name: 'Benin', flag: '🇧🇯' },
  { name: 'Indonesia', flag: '🇮🇩' },
  { name: 'Cape Verde', flag: '🇨🇻' },
  { name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { name: 'Laos', flag: '🇱🇦' },
  { name: 'Uganda', flag: '🇺🇬' },
  { name: 'Andorra', flag: '🇦🇩' },
  { name: 'Burundi', flag: '🇧🇮' },
  { name: 'South Africa', flag: '🇿🇦' },
  { name: 'France', flag: '🇫🇷' },
  { name: 'Libya', flag: '🇱🇾' },
  { name: 'Mexico', flag: '🇲🇽' },
  { name: 'Gabon', flag: '🇬🇦' },
  { name: 'North Macedonia', flag: '🇲🇰' },
  { name: 'China', flag: '🇨🇳' },
  { name: 'Yemen', flag: '🇾🇪' },
  { name: 'Solomon Islands', flag: '🇸🇧' },
  { name: 'Uzbekistan', flag: '🇺🇿' },
  { name: 'Egypt', flag: '🇪🇬' },
  { name: 'Senegal', flag: '🇸🇳' },
  { name: 'Sri Lanka', flag: '🇱🇰' },
  { name: 'Bangladesh', flag: '🇧🇩' },
  { name: 'Peru', flag: '🇵🇪' },
  { name: 'Singapore', flag: '🇸🇬' },
  { name: 'Turkey', flag: '🇹🇷' },
  { name: 'Afghanistan', flag: '🇦🇫' },
  { name: 'United Kingdom', flag: '🇬🇧' },
  { name: 'Zambia', flag: '🇿🇲' },
  { name: 'Finland', flag: '🇫🇮' },
  { name: 'Niger', flag: '🇳🇪' },
  { name: 'Guinea-Bissau', flag: '🇬🇼' },
  { name: 'Azerbaijan', flag: '🇦🇿' },
  { name: 'Djibouti', flag: '🇩🇯' },
  { name: 'North Korea', flag: '🇰🇵' },
  { name: 'Mauritius', flag: '🇲🇺' },
  { name: 'Colombia', flag: '🇨🇴' },
  { name: 'Greece', flag: '🇬🇷' },
  { name: 'Croatia', flag: '🇭🇷' },
  { name: 'Morocco', flag: '🇲🇦' },
  { name: 'Algeria', flag: '🇩🇿' },
  { name: 'Netherlands', flag: '🇳🇱' },
  { name: 'Sudan', flag: '🇸🇩' },
  { name: 'Fiji', flag: '🇫🇯' },
  { name: 'Liechtenstein', flag: '🇱🇮' },
  { name: 'Nepal', flag: '🇳🇵' },
  { name: 'Georgia', flag: '🇬🇪' },
  { name: 'Pakistan', flag: '🇵🇰' },
  { name: 'Monaco', flag: '🇲🇨' },
  { name: 'Botswana', flag: '🇧🇼' },
  { name: 'Lebanon', flag: '🇱🇧' },
  { name: 'Papua New Guinea', flag: '🇵🇬' },
  { name: 'Dominican Republic', flag: '🇩🇴' },
  { name: 'Qatar', flag: '🇶🇦' },
  { name: 'Madagascar', flag: '🇲🇬' },
  { name: 'India', flag: '🇮🇳' },
  { name: 'Syria', flag: '🇸🇾' },
  { name: 'Montenegro', flag: '🇲🇪' },
  { name: 'Eswatini', flag: '🇸🇿' },
  { name: 'Paraguay', flag: '🇵🇾' },
  { name: 'El Salvador', flag: '🇸🇻' },
  { name: 'Ukraine', flag: '🇺🇦' },
  { name: 'Namibia', flag: '🇳🇦' },
  { name: 'United Arab Emirates', flag: '🇦🇪' },
  { name: 'Bulgaria', flag: '🇧🇬' },
  { name: 'Germany', flag: '🇩🇪' },
  { name: 'Cambodia', flag: '🇰🇭' },
  { name: 'Iraq', flag: '🇮🇶' },
  { name: 'Sweden', flag: '🇸🇪' },
  { name: 'Cuba', flag: '🇨🇺' },
  { name: 'Kyrgyzstan', flag: '🇰🇬' },
  { name: 'Russia', flag: '🇷🇺' },
  { name: 'Malaysia', flag: '🇲🇾' },
  { name: 'São Tomé and Príncipe', flag: '🇸🇹' },
  { name: 'Cyprus', flag: '🇨🇾' },
  { name: 'Canada', flag: '🇨🇦' },
  { name: 'Malawi', flag: '🇲🇼' },
  { name: 'Saudi Arabia', flag: '🇸🇦' },
  { name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { name: 'Ethiopia', flag: '🇪🇹' },
  { name: 'Spain', flag: '🇪🇸' },
  { name: 'Slovenia', flag: '🇸🇮' },
  { name: 'Oman', flag: '🇴🇲' },
  { name: 'San Marino', flag: '🇸🇲' },
  { name: 'Lesotho', flag: '🇱🇸' },
  { name: 'Marshall Islands', flag: '🇲🇭' },
  { name: 'Iceland', flag: '🇮🇸' },
  { name: 'Luxembourg', flag: '🇱🇺' },
  { name: 'Argentina', flag: '🇦🇷' },
  { name: 'Nauru', flag: '🇳🇷' },
  { name: 'Dominica', flag: '🇩🇲' },
  { name: 'Costa Rica', flag: '🇨🇷' },
  { name: 'Australia', flag: '🇦🇺' },
  { name: 'Thailand', flag: '🇹🇭' },
  { name: 'Haiti', flag: '🇭🇹' },
  { name: 'Tuvalu', flag: '🇹🇻' },
  { name: 'Honduras', flag: '🇭🇳' },
  { name: 'Equatorial Guinea', flag: '🇬🇶' },
  { name: 'Saint Lucia', flag: '🇱🇨' },
  { name: 'Belarus', flag: '🇧🇾' },
  { name: 'Latvia', flag: '🇱🇻' },
  { name: 'Palau', flag: '🇵🇼' },
  { name: 'Philippines', flag: '🇵🇭' },
  { name: 'Denmark', flag: '🇩🇰' },
  { name: 'Cameroon', flag: '🇨🇲' },
  { name: 'Guinea', flag: '🇬🇳' },
  { name: 'Bahrain', flag: '🇧🇭' },
  { name: 'Suriname', flag: '🇸🇷' },
  { name: 'DR Congo', flag: '🇨🇩' },
  { name: 'Somalia', flag: '🇸🇴' },
  { name: 'Czechia', flag: '🇨🇿' },
  { name: 'Vanuatu', flag: '🇻🇺' },
  { name: 'Togo', flag: '🇹🇬' },
  { name: 'Kenya', flag: '🇰🇪' },
  { name: 'Rwanda', flag: '🇷🇼' },
  { name: 'Estonia', flag: '🇪🇪' },
  { name: 'Romania', flag: '🇷🇴' },
  { name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { name: 'Guyana', flag: '🇬🇾' },
  { name: 'Timor-Leste', flag: '🇹🇱' },
  { name: 'Vietnam', flag: '🇻🇳' },
  { name: 'Uruguay', flag: '🇺🇾' },
  { name: 'Vatican City', flag: '🇻🇦' },
  { name: 'Austria', flag: '🇦🇹' },
  { name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { name: 'Turkmenistan', flag: '🇹🇲' },
  { name: 'Mozambique', flag: '🇲🇿' },
  { name: 'Panama', flag: '🇵🇦' },
  { name: 'Micronesia', flag: '🇫🇲' },
  { name: 'Ireland', flag: '🇮🇪' },
  { name: 'Norway', flag: '🇳🇴' },
  { name: 'Central African Republic', flag: '🇨🇫' },
  { name: 'Burkina Faso', flag: '🇧🇫' },
  { name: 'Eritrea', flag: '🇪🇷' },
  { name: 'Tanzania', flag: '🇹🇿' },
  { name: 'South Korea', flag: '🇰🇷' },
  { name: 'Jordan', flag: '🇯🇴' },
  { name: 'Mauritania', flag: '🇲🇷' },
  { name: 'Lithuania', flag: '🇱🇹' },
  { name: 'Slovakia', flag: '🇸🇰' },
  { name: 'Angola', flag: '🇦🇴' },
  { name: 'Kazakhstan', flag: '🇰🇿' },
  { name: 'Moldova', flag: '🇲🇩' },
  { name: 'Mali', flag: '🇲🇱' },
  { name: 'Armenia', flag: '🇦🇲' },
  { name: 'Samoa', flag: '🇼🇸' },
  { name: 'Japan', flag: '🇯🇵' },
  { name: 'Bolivia', flag: '🇧🇴' },
  { name: 'Chile', flag: '🇨🇱' },
  { name: 'United States', flag: '🇺🇸' },
  { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { name: 'Seychelles', flag: '🇸🇨' },
  { name: 'Guatemala', flag: '🇬🇹' },
  { name: 'Ecuador', flag: '🇪🇨' },
  { name: 'Tajikistan', flag: '🇹🇯' },
  { name: 'Malta', flag: '🇲🇹' },
  { name: 'Gambia', flag: '🇬🇲' },
  { name: 'Nigeria', flag: '🇳🇬' },
  { name: 'Bahamas', flag: '🇧🇸' },
  { name: 'Kuwait', flag: '🇰🇼' },
  { name: 'Maldives', flag: '🇲🇻' },
  { name: 'South Sudan', flag: '🇸🇸' },
  { name: 'Iran', flag: '🇮🇷' },
  { name: 'Albania', flag: '🇦🇱' },
  { name: 'Brazil', flag: '🇧🇷' },
  { name: 'Serbia', flag: '🇷🇸' },
  { name: 'Belize', flag: '🇧🇿' },
  { name: 'Myanmar', flag: '🇲🇲' },
  { name: 'Bhutan', flag: '🇧🇹' },
  { name: 'Venezuela', flag: '🇻🇪' },
  { name: 'Liberia', flag: '🇱🇷' },
  { name: 'Jamaica', flag: '🇯🇲' },
  { name: 'Poland', flag: '🇵🇱' },
  { name: 'Brunei', flag: '🇧🇳' },
  { name: 'Comoros', flag: '🇰🇲' },
  { name: 'Tonga', flag: '🇹🇴' },
  { name: 'Kiribati', flag: '🇰🇮' },
  { name: 'Ghana', flag: '🇬🇭' },
  { name: 'Chad', flag: '🇹🇩' },
  { name: 'Zimbabwe', flag: '🇿🇼' },
  { name: 'Mongolia', flag: '🇲🇳' },
  { name: 'Portugal', flag: '🇵🇹' },
  { name: 'Republic of the Congo', flag: '🇨🇬' },
  { name: 'Belgium', flag: '🇧🇪' },
  { name: 'Israel', flag: '🇮🇱' },
  { name: 'New Zealand', flag: '🇳🇿' },
  { name: 'Nicaragua', flag: '🇳🇮' },
];
